### ISSUE TITLE
Best way to fixed navbar

### ISSUE THREAD

**Issue by mhagnumdw** [sylhare/Type-on-Strap#151]
What is the best way?

I added the properties below to the `site-header` class and now the navbar remains at the top even after the scroll:
```css
.site-header {
    position: fixed;
    z-index: 1000;
```

Now I have to solve it in a satisfactory way so that the part after the navbar does not overlap.

**Comment by sylhare** [comment]
Oh, you'd like to do some facebook effect where when you scroll the navbar stays on top of he page right?
As far as I know you are in the right direction. I would check the css of what's overlapping, it might be because of the `z-index` value.

I would need to try and test it myself, but I might work on the previously raised issues. In case you find something before I look at it let me know. I am interested, if it renders great I might add that as a feature :stuck_out_tongue:

**Comment by mhagnumdw** [comment]
> Oh, you'd like to do some facebook effect where when you scroll the navbar stays on top of he page right?

I don't have facebook, but I asked some of my friends and it seems to be! :smiley:

Well... I was able to do almost 100%, **but it lacks a dynamic fit in the `content` class** that I do not know how to do. Below I will leave my modifications. I can create a fork if you find it necessary.

**_sass/includes/_navbar.scss**
```scss
.site-header {
    ...
    // added
    position: fixed;
    top: 0;
    z-index: 1000;
    border-bottom: 1px solid $border-color; // optional
    ...
```

**_sass/layouts/_default.scss** (_I needed to create this file_)
```scss
.content {
    // TODO: How to calculate dynamically?
    margin-top: 97px; // Because the navbar is fixed
}
```

**_sass/type-on-strap.scss**
```scss
...
// added
@import 'layouts/default';
...
```

**Demo**
![Peek 2019-05-24 11-03 - otimizado](https://user-images.githubusercontent.com/17688846/58334016-0d0ed680-7e15-11e9-9691-b096ee8664ed.gif)

**Comment by sylhare** [comment]
😮 it looks nice!

For the size of the bar, I don't think there's a variable somewhere. It may be due to the size of the icon on the top left plus the margin. 
I think the height of the bar changes with the width of the window (for mobile usage). 

By the way how do you do those nice looking gif, is it some kind of tool that do it for you?

**Comment by mhagnumdw** [comment]
> I think the height of the bar changes with the width of the window (for mobile usage).

Yes!

![image](https://user-images.githubusercontent.com/17688846/58353532-19128c80-7e45-11e9-91dc-b43e3f9555b8.png)
1680x625px, top bar looks cool!


![image](https://user-images.githubusercontent.com/17688846/58353662-78709c80-7e45-11e9-86a5-b8d1aa399fdd.png)
832x608px, there is an unwanted space between the top bar and the banner

> By the way how do you do those nice looking gif, is it some kind of tool that do it for you?

I'm using the [peek](https://github.com/phw/peek) to record the screen.
And for screenshot I'm using [flameshot](https://github.com/lupoDharkael/flameshot).
I really like these tools!

**Comment by sylhare** [comment]
Thanks for the tools!

For the banner, I remember it being a pain to adjust the icon with the text and make sure everything was aligned. 
Here the main problem is that the icon size is fixed to `3em`, however the padding is `2%` on the bottom and `1%` on the top.
