### ISSUE TITLE
a question about the blog

### ISSUE THREAD

**Issue by Joneszero** [sylhare/Type-on-Strap#164]
hi there, i forked your project 'Type-on-Strap' not long ago. when i use it as the module of my blog, i can't see the posts in my homepage,  what problems do you think might be?

sincerely

**Comment by sylhare** [comment]
Hi!

Thanks for using the theme.

The reason you do not see the posts is because you have `index.md` and `index.html`:
  - The file called `index` as the home page of your site.
  - The blog page is generate with ```layout: home```
Having both `index` files generates a conflict for Jekyll it seems

I guess you could move the content of `index.md` into `about.md` or some other page so you can remove the conflicting `index.md`.

Also, in your `_config.yml` file you can just let baseurl empty `baseurl: ""` so the blog url is `https://joneszero.github.io/` instead of `https://joneszero.github.io/joneszero.github.io/`

Let me know if that works for you 😉

**Comment by Joneszero** [comment]
Hi, thanks a lot, your help works for my problem.

Thanks for solving such a simple question, but it is very important to me, to a beginner.

Sincerely

**Comment by sylhare** [comment]
No problems, I am glad I could help! 😃 

I will close this issue then.
