### ISSUE TITLE
Why is my github pages not working with the template?

### ISSUE THREAD

**Issue by sylhare** [sylhare/Type-on-Strap#17]
Allo,

So I create this issue to tackle the possible issues / questions you might have with working with a template on github page.
Either because you have made some customisation, or there's something that needs to be configured.

- [Jekyll troubleshoot guide](https://jekyllrb.com/docs/troubleshooting/).

**Comment by Sylhare** [comment]
So here are the possible reason

1. You need to configure the `base url` or `site url` in `_config.yml` as mentionned in the [readme](https://github.com/Sylhare/Type-on-Strap#site-configuration)
2. You are using a template that require a plugin not accepted by github ([accepted plugins](https://pages.github.com/versions/))
   - On local in your Gemfile try to use `gem 'github-pages'` and see if you get an error
3. You might receive a build error message on your mail account, you can reply for more information or start troubleshooting with [github's documentation](https://help.github.com/articles/troubleshooting-github-pages-builds/).

**Comment by Ian-Goode** [comment]
I am having some problems trying to get github-pages to properly process the website, at the moment the gh-pages website looks like just HTML crap because its not being created correctly.  (this was happening since I forked your theme)
I can build the website properly by using bundle exec jekyll serve and do some local edits, but I am unable to successfully run jekyll serve without any errors involving the versions.
Do you know how to solve this issue?

**Comment by Sylhare** [comment]
Allo, 

I think it is option 1 for you ;
You need to update the `_config.yml` in the master branch of your personal repository (ian-goode.github.io) with which the github page will be generate.

Try with that site configuration
```yml
# SITE CONFIGURATION
baseurl: ""
url: "https://ian-goode.github.io"
````

**Comment by Ian-Goode** [comment]
That was completely my bad... I had thought I committed my local changes to github.

My site is looking amazing! Thanks for your awesome and easily modifiable theme :)

**Comment by mounica-munnaluri** [comment]
Hi,
I am getting site with just html
I am not getting images and css
Could u please help.

<img width="1381" alt="screen shot 2018-01-25 at 11 25 43 am" src="https://user-images.githubusercontent.com/19848774/35408033-93e336fe-01c2-11e8-9aa5-500381be0487.png">

**Comment by frigaut** [comment]
Hi Sylhare,

First of, a big thank you for the great work. Difficult to make a simpler installation (well mostly thanks to Jekyll), and the theme is really super nice and has most features I wanted. So thanks for making it available.

One short question: I don't remember how to change the text that appears in the browser tab (the one with the favicon that says "Simplistic, responsive jekyll based open source theme"?

Cheers & Congrats,
Francois

**Comment by Sylhare** [comment]
Hi @frigaut,

Well that text is generated by the browser, it does that on https://sylhare.github.io/Type-on-Strap/ because it is the site generated from the repo.

However locally it is displaying at http://localhost:4000/Type-on-Strap/ the site address: `http://localhost:4000/Type-on-Strap/`.

Did you try it on your side and still seeing the `Simplistic, responsive jekyll based open source theme` text? As of now it is not yet customizable.

**Comment by sunh20** [comment]
Hi,

I'm having a similar issue where only the HTML is loading and nothing else, but this is only an issue when I'm making a website for a github organization page instead of a user page. Doing it on my user page, I was able to just change the one url line in the _config file and have the site load properly, but I did the exact same thing with the organization page and it doesn't load properly. 

When I run a local server, everything shows up just fine. Any ideas?

Thanks!

**Comment by sylhare** [comment]
Link back https://github.community/t5/GitHub-Pages/Pages-theme-not-work/m-p/43141/highlight/false#M2483 
If you have any issue with the theme not solved here, or in another already closed issue, feel free to ask 😉

**Comment by buenourbano** [comment]
Hi,

I have an issue with the gallery page on my organizations web (https://thefluxions.github.io/gallery). It shows the pics I added to the pexels folder, but I deleted your pics from the folder and still shows. I checked gallery.md file and gallery.html file and still couldn't find the reason why happens.

By the way, it's a great and flexible design.

Thanks so much in advance :)

**Comment by sylhare** [comment]
Hi @buenourbano I have created #211 for your issue, I'll take a look at it, thanks for reporting ;)

**Comment by sylvietht** [comment]
Hi,

Thanks so much for this great and easy-to-use theme. I'm in the process of redoing my organization's website (just building locally at the moment) and am trying to get the blog feed to live on a different page (/blog) and have a static homepage.

I tried creating a new layout called `blog`, which is a copy of the existing `home` layout. Then I removed `{% include blog.html %}` from the `home` layout. Then I created a page in `pages` called `blog.html` with the `blog` layout. I've tried a few different variations of this, and in every case it seems like the blog feed isn't able to generate in any file other than `index.html`. Any insights as to what is needed in order to move the blog feed away from the homepage?

Thanks so much!

**Comment by sylhare** [comment]
Hey @sylvietht is your use case similar to #104 _"How to create page in navbar with link to blog post overview?"_ ?

**Comment by sylvietht** [comment]
Thanks for the quick response @sylhare - yes, my use case is similar to that, except I'd like to keep the blog feed out of index.html altogether, so I suspect the fix isn't quite as simple as it was in #104.

I thought it might be something with the paginator. Is there an easy way to change the url that the paginator uses? I'm looking at it now and don't see it, but if you have any ideas...

Let me know if you'd like to see any of my code. Thanks so much for your help!

**Comment by sylhare** [comment]
Yes I think it is an issue with paginator, https://github.com/sverrirs/jekyll-paginate-v2/issues/21 seems to talk about it, but I don't remember what you need to modify in your config. I'll go take a look and create a new issue for this specific use case.

I'll get back to you if I find anything 😉

**Comment by sylvietht** [comment]
Awesome, thanks so much for that link - I'll do some reading too.

**Comment by julia-neme** [comment]
Hi sylhare, thanks for sharing this lovely template! I have cloned the repo and changed the url to point to my own website (julia-neme.github.io) as suggested in the readme.. but it is not rendering properly. Do I have to do anything else in settings or config?
