### ISSUE TITLE
Feature image caption & disabling avatar in _config.yml. 

### ISSUE THREAD

**Issue by senemp** [sylhare/Type-on-Strap#174]
Hi, 

Thank you for the theme. I'm still very new at Jekyll (and coding) and learning slowly. I have three questions and I would appreciate the help. 

- Is it possible to add captions to the "freature-img"- preferably on the image itself, at the bottom corner with a small font? 
- Also, how can I disable avatar image in the _config.yml. When I erase the code, it still acts as an image is missing - "logo.img" (see the image) 
- How can I align the header_text to the left? And how can I change the font for the header_text? 

Many thanks! 

<img width="1666" alt="Screen Shot 2019-07-25 at 2 02 33 PM" src="https://user-images.githubusercontent.com/15858372/61869919-77abc380-aee5-11e9-9814-96ed6f06dc57.png">

**Comment by sylhare** [comment]
Hi Thanks for using the theme:

- As of now, there's no feature to have a caption in the `feature-img`. Would you be able to show me how it would look like on the picture, it might not be hard to add.

- If you want to make the missing image disappear, you can put a blanck image (that's kinda hacky). If you remove the html code for the image it should disappear. It should be in `navbar` something like `<img src="..." \>`. However I am not sure what the css will do, let me know how it goes 😅 

- To align the header text, you would need to go into the `_sass > layouts > _post.scss` and play with the css of the `header` with something like `text-align: left;` instead of `center`.

- To change the header font you would need to change in the `_sass > base > variables.scss` file the value of `$font-family-logo: 'Source Sans Pro', Helvetica, Arial, sans-serif;`. Instead of `'Source Sans Pro'` add the one you would like. (The "default" font would work without any more work, if you use a custom one, look at how it was done with `Pacifico`).

**Comment by senemp** [comment]
Sorry for the late reply. 

- I was thinking something like this for the image capture -- see the right corner: 

<img width="1669" alt="Screen Shot 2019-07-25 at 6 12 06 PM" src="https://user-images.githubusercontent.com/15858372/62424693-f7ead980-b6da-11e9-8299-c62c5ea12016.png">

- I couldn't figure it out how to align the header_text on the main page. When I change the text_align in _post.scss, it changes the header to the left but when you click on the post. I want the align the main "header_text" that is written on the "header_feature_image". Is this possible to do?
