### ISSUE TITLE
Black thumbnails when sharing on social media

### ISSUE THREAD

**Issue by sylhare** [sylhare/Type-on-Strap#220]
From @rosepac in #218

A silly doubt, using thumbnail + feature-img. Should generate image thumbnail for social media?
 I've been passing some links from your blog. To try..

It is rare because when trying to share on Facebook, sometimes the link box appears but the image is black. 
![image](https://user-images.githubusercontent.com/4309005/88810515-bd186600-d1b5-11ea-97ef-ba9aae412aa9.png)

And with other links. Load "a box" that says github error..
![image](https://user-images.githubusercontent.com/4309005/88810596-dc16f800-d1b5-11ea-9b2b-9562b3d0107e.png)

Some idea for this? 🙈

_Originally posted by @rosepac in https://github.com/sylhare/Type-on-Strap/issues/218#issuecomment-665692788_

**Comment by sylhare** [comment]
I am gonna try it using your blog to see what's the meta is taking as img. It could be the seo tag, or the yaml or something else.

**Comment by sylhare** [comment]
So from what I look the black image would be because of the image format that is used and that may not be compatible, or the link to the image might not be found:

- webP is quite a new format and might have compatibility issues: https://caniuse.com/#search=webp and [google FAQ on webp](https://developers.google.com/speed/webp/faq)
- Make sure that you use the right path, preferably under quotes. Also by default if no thumbnail (smaller size of the feature-img), it will take the feature-img as the thumbnail for the meta. Here is the example:
```yaml
feature-img: "assets/img/pexels/circuit.jpeg"
```

Did you have any warning or errors when deploying your webiste on github page?
When I try to run your site locally, I get some `Error: YAML Exception reading`. Did you change something in the url (or link) of the posts / pages you want to share? (that may have impacted the seo tags that is trying to create the meta with the wrong information making a "site not found" error when sharing)

**Comment by rosepac** [comment]
Ok, I have already found the error that was shown when trying to publish the links from facebook and other RRSS. In facebook (Site Not Found - Github Pages).
- This was because the Github repository url was not changed with the custom domain. In the configuration document `_config.yml` in the line of the `url:`. When using a custom domain. It must be changed `namegithub.github.io/` for the `url_used.com`.

I realized the bug, after realizing that there was also a bug with the canonical urls. Were being generated of the type `https://rosepac.github.io/URL-that-use-in-the-permalink/`

Now. I see it in the Facebook. I now see my "page avatar" image when sharing any of my links. And the URL canonical are correct. With my URL.
![image](https://user-images.githubusercontent.com/4309005/90645861-c174f380-e236-11ea-9ca9-78dea3314e39.png)
![image](https://user-images.githubusercontent.com/4309005/90646091-131d7e00-e237-11ea-922d-c37768e5eb68.png)


The fact that the inserted image is not published as a feature through RRSS. It seems that it is because of the image format. Although I have put `jpg` images in the feature and in the thumbnail and it still does not show it as a featured image in RRSS.

I'll keep investigating.. 🙈
