### ISSUE TITLE
Cannot see maths equation in markdown

### ISSUE THREAD

**Issue by franloradr** [sylhare/Type-on-Strap#221]
It shows LaTeX code:

[2014-11-28-markdown-and-html.md](https://sylhare.github.io/Type-on-Strap/2014/11/28/markdown-and-html.html)

In my case, I solved with this script in _layouts/post.html

```
<!-- MathJax -->
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

**Comment by sylhare** [comment]
So I kept Katex: https://katex.org/ because it is to be faster than MatJax.
I fixed the rendering issue by using the latest version with the auto render, (I had a init_katex.js that was doing that for me before).

And now it's all good. 
Your alternative with MatJax works as well, since both MatJax and Katex works with the same syntax. 
Thanks 👍
