### ISSUE TITLE
how to add content in the home page without blog posts

### ISSUE THREAD

**Issue by jingpengw** [sylhare/Type-on-Strap#364]
Hi, thank you for making this excellent package!

I do not need blogs but I would like to add some simple texts and images. Markdown would be better than HTML for me.

After deleting all the blog posts, I still do not know how to add content to the home page...

This is the home page I am having.
<img width="1775" alt="Screen Shot 2022-10-05 at 8 13 33 PM" src="https://user-images.githubusercontent.com/7651573/194186081-26d70be4-a631-4aa2-b354-940023d2082c.png">

**Comment by sylhare** [comment]
For that you can update the index.html to point to a new layout, right now it points to home which is: https://github.com/sylhare/Type-on-Strap/blob/master/_layouts/home.liquid

You can create another one in markdown or override it for your use case.

**Comment by jingpengw** [comment]
thank you for the reply!

unfortunately, I do not have experience with web development and still have not figured it out!
could you please explain it a little bit more?

**Comment by sylhare** [comment]
Yep as long as it works for you 👍 as long as the `index.html` has `introduction` as layout it should work fine.
Closing for now.

**Comment by jingpengw** [comment]
the problem is that the home page is empty, and I still don't know how to add content.

**Comment by sylhare** [comment]
Do you have a link to the Repo?

**Comment by sylhare** [comment]
So from what I see:
- There are no `introduction.liquid` (you can use `.md` as well) file in the `_layout` folder, (you can also use the `page` layout instead of the `default` layout as base at the top).
- You did not update `index.html` to put `introduction` which is your new layout without the blogging part.

Once you do that you can put all the content you want in the introduction layout where the include blog part was.
