### ISSUE TITLE
Search does not work correctly

### ISSUE THREAD

**Issue by Jeansen** [Sylhare/Type-on-Strap#39]
If I try the search, it totally does not behave as expected. For instance, I can type in words that do not exist, but it shows me a lot of posts, anyway. It looks like the search goes character by character. 

If I type in aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa i can narrow down the result to one post, If I type in xxxxxxxxxxxxxxxxxxx I get now result, since there a no posts with that many x.

**Comment by Sylhare** [comment]
Hi @Jeansen 

I am using Christian Fei's [Simple Jekyll Search](https://github.com/christian-fei/Simple-Jekyll-Search) for my search page.
If you want to look for a particular work, you should try: `"word"` instead of `word`.

I have updated the search feature, but it seems the behaviour you mentioned is still here. You can try open an issue on the plugin page:

- https://github.com/christian-fei/Simple-Jekyll-Search/issues

**Comment by Jeansen** [comment]
Hi @Sylhare 
Thank you very much!

**Comment by tahoward** [comment]
This behavior seems to go away if `fuzzy` argument in `SimpleJekyllSearch` is set to false.

**Comment by Sylhare** [comment]
Oh thanks!! I'll try that out :)

**Comment by Sylhare** [comment]
I have updated it, it is now working!
Big thanks @tahoward for finding out the solution ;)
