### ISSUE TITLE
Links pointing to localhost

### ISSUE THREAD

**Issue by schneidr** [Sylhare/Type-on-Strap#49]
Some links are pointing to `localhost:4000` even though I've set the actual address of the Apache server in `baseurl` and `url` in `_config.yml`.

Examples:

- RSS feed
- search
- tags
- portfolio

I have not modified the links in `navbar.html`:

    <a class="clear" href="{{ site.url }}{{ site.baseurl }}/search">

**Comment by Sylhare** [comment]
Do you know which links are pointing there? I will take a look into navbar.html and around in the code. Might be a mistake.

**Comment by Sylhare** [comment]
Hi, so I have checked on my side and I don't think the theme have any misplaced links (like localhost would be hard coded in them) or I didn't find them.

So my guess is that the problem comes from the way the jekyll website is launched on your server. If you are running it locally on your server then it might always be referring to the localhost.
(For example if I run master locally it will run under "localhost" eventhough `_config.yml` says `sylhare.github.io` as baseurl.

**Comment by schneidr** [comment]
Sorry, my fault. After reading [the documentation](https://jekyllrb.com/docs/usage/#override-default-development-settings) again I learned that I have to set the environment variable `JEKYLL_ENV=production` to tell jekyll to use the value defined in `_config.yml` instead of the default `localhost:4000`.
