### ISSUE TITLE
Project Translation in Spanish

### ISSUE THREAD

**Issue by Talpio** [Sylhare/Type-on-Strap#50]
A simple question: Can I translate this project?

**Comment by Sylhare** [comment]
Hi !

- What do you mean? is it like a new feature to have the website in both language (switching from one to the other?)

- Or is it to write the documentation in another language?

Because you can change the keywords in the `_config.yml` to any language you wish. Let me know so I can see how we can make it fit in here. ;)

**Comment by Talpio** [comment]
It's to write the documentation in Spanish.

**Comment by Sylhare** [comment]
Yeah sure thanks ;)

**Comment by Sylhare** [comment]
@Talpio I am gonna close for now since I don't see any movement. Please don't hesitate to make a PR when you have it ready 😉

**Comment by mcavazotti** [comment]
Hi! I just cloned your template. Thank you for your hard work!
So, is there a way to have the website in both languages? (for me it would be Portuguese and English :grimacing:  )

**Comment by sylhare** [comment]
Hi, as for now, it's not possible.

The only workaround to do it would be to have like two repository one english, one portuguese and make a button to switch from one another (using like base_url / portuguese and base_url / english ).
Not very practical though.
