### ISSUE TITLE
post-teaser as article tag?

### ISSUE THREAD

**Issue by yshrsmz** [Sylhare/Type-on-Strap#54]
[Currently `post-teaser` class is on `div` tag. ](https://github.com/Sylhare/Type-on-Strap/blob/544e4ab808706194b488c8cebce9e2fc9f0b6021/_layouts/home.html#L15)
But to make it more semantic, wouldn't it be better to use `article` tag instead of `div`?

**Comment by Sylhare** [comment]
Hi!

I'll dig into that, thanks.

**Comment by Sylhare** [comment]
Well since the css is made of the `<div>` and the `post-teaser`, I see no value in going through the css to update for having it as `<article>`. 

However, I might not be award of the advantages of the `<article>` tag. If you have some documentation, I would be glad to look into it. 

I don't plan for now to make any change, but I'd gladly accept a pull request :wink:
I will close it for now.
