### ISSUE TITLE
Duplication of Home page when enabled

### ISSUE THREAD

**Issue by azmirfakkri** [Sylhare/Type-on-Strap#73]
When I added title to the index.html, the Home tab is shown twice. 

<img width="460" alt="screen shot 2018-05-03 at 15 29 40" src="https://user-images.githubusercontent.com/33866698/39582949-f0b0c1b4-4ee6-11e8-815c-dee88eaec108.png">

The first Home redirects to the first page of blog posts and the second Home redirects to the second page of blog posts. 

I'd like to just show one Home tab which will re-direct to all the blog posts.

**Comment by Sylhare** [comment]
Oh, I will take a look at it. Thanks

**Comment by Sylhare** [comment]
Hi so I have looked into it, the `index.html` is not really supposed to be a page per say which means it is not supposed to get a title.
With a title since the index uses the `paginator` plugins it creates pages of all of the blog posts in the `_blog/` directory.

Now that I have enough article to get two pages, I realise that it creates enough a title for each page rendered by the `index.html`.

So I am looking if I can still implement this feature and how.

**Comment by Sylhare** [comment]
Yup so to fix it, I changed the rendering of the title, by making sure that a title is only present once. Which means two pages with the same title only one will be rendered.

Cheap fix, but `jekyll-paginate` eventhough it is the only version of paginate that I know which works on Github Pages is now deprecated. Should be good enough

**Comment by azmirfakkri** [comment]
Perfect! Thank you!
